### ISSUE TITLE
Enhancement: Delete DataObject by class name and URL Route/ID

### ISSUE THREAD

**Issue by dmc-core** [silverleague/silverstripe-console#28]
For example:

```
ssconsole dataobject:delete [ClassName] [ID or URL route]
# Specific: ssconsole dataobject:delete Page /path/to/my/bad/page

Are you sure you want to delete this object? [yes]
[ClassName] #[ID]/with route [URL route] deleted.
```

**Comment by robbieaverill** [comment]
I guess we'd need to double check that the CLI has admin permissions for this.

**Comment by robbieaverill** [comment]
I've just re-read this - I don't really like the route option. It would mostly be useful for SiteTree routes I suppose, but I think this could open a can of UX worms that might be best left closed.

I think we'll close this for now. Feel free to reopen if you really want it!
