### ISSUE TITLE
ssconsole refuses to run with "SilverStripe installation could not be found"

### ISSUE THREAD

**Issue by oddnoc** [silverleague/silverstripe-console#51]
ssconsole (version 0.1.0 and 0.2.0 equally; installed locally or globally) fails as shown in the transcript below (transcript was made with local installation). As shown, there is definitely a SilverStripe installation, because `sake dev/build` just ran successfully. 

```
…
 * UserDefinedForm_EmailRecipient
 * UserDefinedForm_EmailRecipientCondition
 * SubmittedForm
 * SubmittedFormField
 * SubmittedFileField

 Database build completed!

╭─vagrant@example.vg.example.com ~/Project/docroot  ‹develop› 
╰─➤  vendor/bin/ssconsole dev:build --flush
A SilverStripe installation could not be found. Please run ssconsole from your SilverStripe root.
╭─vagrant@example.vg.example.com ~/Project/docroot  ‹develop› 
╰─➤  
```

The host system is FreeBSD 10.3-RELEASE-p4 amd64 running PHP 5.6.32 and mariadb Ver 15.1 Distrib 10.1.30-MariaDB.

**Comment by robbieaverill** [comment]
Thanks for reporting! Which SS version are you running?

**Comment by oddnoc** [comment]
The transcript above was with 3.6.x

**Comment by robbieaverill** [comment]
Right! This is a SS4 only package :-)
