### ISSUE TITLE
Enhancement: Seed database from YML

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-console#53]
A bit like the SilverStripe Seeder, but better

**Comment by axyr** [comment]
Why limit the Seeder to yml format.

I have written hundreds of Seeders in Laravel projects, and a lot of them are used to : 
- Import data from an old site's sql file
- Import data from csv or json file
- Seed development data, with relations set up.
- Enrich and or normalize data while seeding above datasources.

Sometimes you might want to check if a record allready exists.

I think only using yml format will limit the usecases.

I think how Laravel uses Seeder classes with one required run() method very flexible.
You can then do whatever you want in that method in any datasource format you want. Including yml..

**Comment by robbieaverill** [comment]
Good point @axyr - CSV, JSON and YAML seem like reasonable input formats
