### ISSUE TITLE
Combine all console options in to a single solution

### ISSUE THREAD

**Issue by Firesphere** [silverleague/silverstripe-console#57]
Multiple people have written their own implementation of a SilverStripe console.

I would much rather see a single implementation, than the current option of choosing a single one that almost does what is wanted.

@micmania and @axyr have their own implementations. It would be good to get the three options together and look at the pros and cons and take the best of each instead of keeping on trucking the way the current console implementations are all going their separate path of priority

**Comment by robbieaverill** [comment]
Hey @Firesphere, this discussion has been had already (reference: https://github.com/silverleague/silverleague.github.io/issues/1). I'm open to the idea of pull requests, but as far as I know this module is the only console for SilverStripe that currently supports SilverStripe 4.

My surface knowledge of @micmania's console is that is provides a very different use case.

Discussion on comparisons should continue on the issue referenced above so we can keep the context together =)
